name: shbsantri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.12
  dio: ^5.4.2+1
  file_picker: ^8.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_quill: ^9.3.7
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  fpdart: ^1.1.0
  get: 4.6.6
  get_time_ago: ^1.3.1
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  logger: ^2.2.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo/logo.png
    - assets/lottie/lottie_loading.json
