name: shbsantri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  get: 4.6.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  zoom_hover_pinch_image: ^1.0.3
  fpdart: ^1.1.0
  

dev_dependencies:
  logger: ^2.2.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo/logo.png
